PATHS = """R,R,R,R,R,R,R,R,R,D
D,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,D
D,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,D
D,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,D
D,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,D
D,L,L,L,L,L,L,L,L,L
,,,,,,,,,
U,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,U
U,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,U
U,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,U
U,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,U
U,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,U
,,,,,,,,,
D,R,D,R,D,R,D,R,D,R
D,U,D,U,D,U,D,U,D,U
D,U,D,U,D,U,D,U,D,U
D,U,D,U,D,U,D,U,D,U
D,U,D,U,D,U,D,U,D,U
D,U,D,U,D,U,D,U,D,U
D,U,D,U,D,U,D,U,D,U
D,U,D,U,D,U,D,U,D,U
D,U,D,U,D,U,D,U,D,U
R,U,R,U,R,U,R,U,R,U
,,,,,,,,,
L,D,L,D,L,D,L,D,L,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,L,U,L,U,L,U,L,U,L
,,,,,,,,,
R,R,R,R,R,R,R,R,R,U
U,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,U
U,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,U
U,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,U
U,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,U
U,L,L,L,L,L,L,L,L,L
,,,,,,,,,
R,R,R,R,R,R,R,R,R,R
U,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,U
U,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,U
U,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,U
U,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,U
U,L,L,L,L,L,L,L,L,L
,,,,,,,,,
R,R,R,R,R,R,R,R,R,D
U-L,D,L,D,L,D,L,D,L,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,L,U,L,U,L,U,L,U,L
,,,,,,,,,
R,D,R,D,R,D,R,D,R,D
U,R,U,R,U,R,U,R,U,U-R
U,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,U
U,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,U
U,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,U
U,L,L,L,L,L,L,L,L,L
R,R,R,R,R,R,R,R,R,U
,,,,,,,,,
U,D,L,D,L,D,L,D,L,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,D,U,D,U,D,U,D,U,D
U,L,U,L,U,L,U,L,U,L
,,,,,,,,,
D,R,D,R,D,R,D,R,D,U
D,U,D,U,D,U,D,U,D,U
D,U,D,U,D,U,D,U,D,U
D,U,D,U,D,U,D,U,D,U
D,U,D,U,D,U,D,U,D,U
D,U,D,U,D,U,D,U,D,U
D,U,D,U,D,U,D,U,D,U
D,U,D,U,D,U,D,U,D,U
D,U,D,U,D,U,D,U,D,U
R,U,R,U,R,U,R,U,R,U
"""
